# Generated by Django 4.1.7 on 2023-04-13 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_categorysubscriber_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', through='news.CategorySubscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
